'use strict';
// Jeeves boundary: future authorized adapter should return article/order records to this shape.
// No ERP endpoint or credentials are assumed here.
const JeevesAdapter = Object.freeze({available:false, async lookupArticle(){throw new Error('Jeeves är inte anslutet');}});
const KEY='lagerkollen_v2', DB='lagerkollen-backup', STORE='snapshots', CHECKPOINT='lagerkollen_cloud_checkpoint';
const $=id=>document.getElementById(id);
const blank=()=>({orders:[],stock:{},current:null});
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const date=t=>t?new Date(t).toLocaleString('sv-SE',{dateStyle:'short',timeStyle:'short'}):'–';
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,9);
const norm=s=>String(s||'').trim().toUpperCase();
const labels={missing:'Saknas',found:'Hittad',notfound:'Ej hittad'};
let data=blank(), view='order', filter='all', sortBy='default', toastTimer, dbPromise;
let cloudRevision=null, cloudBusy=false, cloudConflict=null, cloudTimer, cloudMessage='Logga in för synk mellan mobil och dator', cloudEmail='';
function sanitize(input){
 if(!input||!Array.isArray(input.orders)||!input.stock||typeof input.stock!=='object'||Array.isArray(input.stock))throw new Error('Ogiltig data');
 const out=blank();out._revision=Number(input._revision)||0;
 out.orders=input.orders.filter(o=>o&&typeof o==='object').map(o=>({id:String(o.id||uid()),name:String(o.name||'Namnlös'),created:Number(o.created)||Date.now(),updated:Number(o.updated)||Number(o.created)||Date.now(),archived:!!o.archived,deletedArticles:Object.fromEntries(Object.entries(o.deletedArticles||{}).filter(([id,time])=>id&&Number.isFinite(Number(time))&&Number(time)>0).map(([id,time])=>[id,Number(time)])),articles:(Array.isArray(o.articles)?o.articles:[]).filter(a=>a&&a.nr).map(a=>({id:String(a.id||uid()),nr:String(a.nr),status:labels[a.status]?a.status:'missing',location:String(a.location||''),note:String(a.note||''),updated:Number(a.updated)||Date.now()}))}));
 for(const [key,x] of Object.entries(input.stock)){if(!x||typeof x!=='object')continue;const k=norm(key||x.nr);if(!k)continue;out.stock[k]={nr:String(x.nr||key),location:String(x.location||''),updated:Number(x.updated)||0,previousLocations:Array.isArray(x.previousLocations)?x.previousLocations.filter(v=>typeof v==='string').slice(0,20):[],lastSeen:Number(x.lastSeen)||0,foundCount:Number(x.foundCount)||0,lastOrder:String(x.lastOrder||''),note:String(x.note||'')};}
 out.current=out.orders.some(o=>o.id===input.current)?input.current:(out.orders.find(o=>!o.archived)||out.orders[0]||{}).id||null;
 return out;
}
function db(){if(!('indexedDB'in window))return Promise.reject(Error('IndexedDB saknas'));if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return dbPromise;}
async function readMirror(){let d=await db();return new Promise((resolve,reject)=>{let r=d.transaction(STORE).objectStore(STORE).get('current');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});}
async function writeMirror(value){let d=await db();return new Promise((resolve,reject)=>{let tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).put(value,'current');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});}
function notice(message){let el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3500)}
function setSaveState(message,issue=false){$('saveState').textContent=message;$('saveState').style.color=issue?'#ffd3a3':'';}
function persist(){data._revision=Math.max(Date.now(),(data._revision||0)+1);let value=JSON.stringify(data),localOK=true;try{localStorage.setItem(KEY,value);setSaveState('Sparad lokalt')}catch(e){localOK=false;setSaveState('Lagring misslyckades',true);notice('Kunde inte spara lokalt. Exportera en backup nu.')}writeMirror(value).then(()=>{if(!localOK)setSaveState('Reservkopia sparad',true)}).catch(()=>{if(!localOK)notice('Ingen lokal lagring fungerar. Exportera nu.')});render();scheduleCloudPush();}
async function boot(){let local=null,mirror=null;try{let raw=localStorage.getItem(KEY);if(raw)local=sanitize(JSON.parse(raw))}catch(e){setSaveState('Lagring kunde inte läsas',true)}try{let raw=await readMirror();if(raw)mirror=sanitize(JSON.parse(raw))}catch(e){}data=mirror&&(!local||mirror._revision>local._revision)?mirror:(local||blank());if(mirror&&mirror===data&&!local){try{localStorage.setItem(KEY,JSON.stringify(data))}catch(e){}notice('Lokal reservkopia återställd')}render();await initCloud();}
function current(){return data.orders.find(o=>o.id===data.current)}
function selectOrder(id){if(!data.orders.some(o=>o.id===id))return;data.current=id;try{localStorage.setItem(KEY,JSON.stringify(data))}catch(e){}writeMirror(JSON.stringify(data)).catch(()=>{});show('order');}
function show(next){view=next;let mobileOrders=next==='orders';$('sidebar').classList.toggle('open',mobileOrders);$('orderView').classList.toggle('hidden',next==='stock'||next==='backup'||mobileOrders);$('stockView').classList.toggle('hidden',next!=='stock');$('backupView').classList.toggle('hidden',next!=='backup');document.querySelectorAll('.mobile-nav button').forEach(b=>b.classList.toggle('selected',b.dataset.view===next));if(next==='stock')$('stockSearch').focus();render();}
function startOrder(){show('orders');$('newOrderForm').classList.remove('hidden');$('orderName').focus();}
function addOrder(name){name=name.trim();if(!name)return;let o={id:uid(),name,created:Date.now(),updated:Date.now(),archived:false,articles:[]};data.orders.unshift(o);data.current=o.id;$('orderName').value='';$('newOrderForm').classList.add('hidden');persist();show('order');$('quickInput').focus();}
function extract(raw){let values=[],ignored=0,lines=raw.split(/\r?\n/),csvHeader=lines.some(line=>/^(artikel(nummer|nr)?|article|item|sku)([,;\t]|$)/i.test(line.trim()));for(const line of lines){let s=line.trim();if(!s)continue;if(/^(artikel(nummer|nr)?|article|item|sku|antal|quantity)\b/i.test(s)){ignored++;continue}let cells=s.includes('\t')?s.split('\t'):s.includes(';')?s.split(';'):csvHeader&&s.includes(',')?s.split(','):null;let tokens;if(cells&&cells.length>1){tokens=[cells[0]]}else{tokens=s.split(/[\s,;]+/)}for(let token of tokens){token=token.replace(/^["'“”\[({]+|["'“”\])}.]+$/g,'').trim();if(!/^[\p{L}\p{N}][\p{L}\p{N}._\/-]*$/u.test(token)||token.length<2||token.length>48){ignored++;continue}values.push(token)}}return {values,ignored};}
function addArticles(raw){let o=current();if(!o)return;let parsed=extract(raw),seen=new Set(o.articles.map(a=>norm(a.nr))),added=0,duplicate=0;for(const nr of parsed.values){let key=norm(nr);if(seen.has(key)){duplicate++;continue}seen.add(key);let old=data.stock[key]||{};o.articles.push({id:uid(),nr,status:'missing',location:old.location||'',note:'',updated:Date.now()});added++}if(added){o.updated=Date.now();persist()}notice(`${added} tillagda${duplicate?` · ${duplicate} dubbletter hoppades över`:''}${parsed.ignored?` · ${parsed.ignored} ogiltiga rader`:''}`);return added;}
function saveField(id,field,value){let a=current()?.articles.find(a=>a.id===id);if(!a)return;value=String(value).trim();if(a[field]===value)return;a[field]=value;a.updated=Date.now();current().updated=a.updated;if(field==='location'&&a.status==='found')rememberFound(a,current(),false);if(field==='note'&&data.stock[norm(a.nr)])data.stock[norm(a.nr)].note=value;persist();}
function rememberFound(a,o,increment){let k=norm(a.nr),x=data.stock[k]||{nr:a.nr,location:'',updated:0,previousLocations:[],lastSeen:0,foundCount:0,lastOrder:'',note:''};if(a.location){let previous=String(x.location||'').trim(),next=a.location.trim();if(previous&&norm(previous)!==norm(next))x.previousLocations=[previous,...(x.previousLocations||[]).filter(p=>norm(p)!==norm(previous)&&norm(p)!==norm(next))].slice(0,20);x.location=next;}x.updated=Date.now();x.lastSeen=x.updated;x.lastOrder=o.name;if(increment)x.foundCount=(x.foundCount||0)+1;if(a.note)x.note=a.note;data.stock[k]=x;}
function changeStatus(id,status){let o=current(),a=o?.articles.find(a=>a.id===id);if(!a||!labels[status])return;let was=a.status;a.status=status;a.updated=Date.now();o.updated=a.updated;if(status==='found'&&was!=='found')rememberFound(a,o,true);persist();if(status==='found'&&!a.location){let field=Array.from(document.querySelectorAll('.article')).find(el=>el.dataset.id===id)?.querySelector('[data-field="location"]');field?.focus();notice('Hittad! Ange lagerplats om du vet den.');}}
function removeArticle(id){let o=current(),a=o?.articles.find(a=>a.id===id);if(!a||!confirm(`Ta bort ${a.nr} från ordern?`))return;o.articles=o.articles.filter(x=>x.id!==id);o.updated=Date.now();(o.deletedArticles??={})[id]=o.updated;persist();}
function updateStock(key,field,value){let x=data.stock[key];if(!x)return;value=value.trim();if(field==='location'&&x.location&&norm(x.location)!==norm(value))x.previousLocations=[x.location,...(x.previousLocations||[]).filter(p=>norm(p)!==norm(x.location))].slice(0,20);x[field]=value;x.updated=Date.now();persist();}
function renderOrders(){let active=data.orders.filter(o=>!o.archived),past=data.orders.filter(o=>o.archived);function rows(list,title){if(!list.length)return '';return `<div class="order-section">${title} · ${list.length}</div>`+list.map(o=>{let missing=o.articles.filter(a=>a.status==='missing').length;return `<button class="order-row ${o.id===data.current?'selected':''}" data-order="${esc(o.id)}"><span class="line"><strong>${esc(o.name)}</strong><span class="count">${missing} saknas</span></span><small>${date(o.created)} · ${o.articles.length} ${o.articles.length===1?'artikel':'artiklar'}</small></button>`}).join('')}$('orders').innerHTML=rows(active,'Aktiva')+rows(past,'Historik')||'<div class="empty" style="margin:10px">Inga ordrar ännu</div>';$('stockCount').textContent=Object.keys(data.stock).length;}
function renderOrder(){let o=current();$('noActive').classList.toggle('hidden',!!o);$('activeWrap').classList.toggle('hidden',!o);if(!o)return;$('orderEyebrow').textContent=o.archived?'ARKIVERAD ORDER':'AKTIV ORDER';$('activeTitle').textContent=`Order ${o.name}`;$('activeMeta').textContent=`Skapad ${date(o.created)} · ${o.archived?'Arkiverad':'Pågående'}`;$('archive').textContent=o.archived?'Återöppna':'Arkivera';$('tot').textContent=o.articles.length;for(const [id,s] of [['mis','missing'],['fnd','found'],['nf','notfound']])$(id).textContent=o.articles.filter(a=>a.status===s).length;renderArticles();}
function renderArticles(){let o=current();if(!o)return;let q=norm($('search').value),arr=o.articles.filter(a=>{let x=data.stock[norm(a.nr)]||{};return(filter==='all'||a.status===filter)&&norm([a.nr,a.location,a.note,x.location,x.note,(x.previousLocations||[]).join(' ')].join(' ')).includes(q)});if(sortBy==='location'||sortBy==='area')arr.sort((a,b)=>{let la=a.location||data.stock[norm(a.nr)]?.location||'',lb=b.location||data.stock[norm(b.nr)]?.location||'';return (!la?1:!lb?-1:la.localeCompare(lb,'sv',{numeric:true}))});if(sortBy==='known')arr.sort((a,b)=>Number(!!(b.location||data.stock[norm(b.nr)]?.location))-Number(!!(a.location||data.stock[norm(a.nr)]?.location)));let content=arr.map(a=>{let old=data.stock[norm(a.nr)]||{},loc=a.location||old.location||'',context=old.lastSeen?`Senast hittad ${date(old.lastSeen)}${old.location?' på '+old.location:''}`:loc?'Känd plats':'Ingen tidigare plats';if(old.lastOrder)context+=' · Order '+old.lastOrder;if(old.note)context+=' · '+old.note;if((old.foundCount||0)>=3&&a.status!=='found')context+=' · Återkommande artikel';return `<div class="article ${a.status}" data-id="${esc(a.id)}"><div class="identity"><div class="number">${esc(a.nr)}</div><div class="context">${esc(context)}</div></div><div class="location"><label class="sr-only" for="loc-${esc(a.id)}">Lagerplats för ${esc(a.nr)}</label><input id="loc-${esc(a.id)}" data-field="location" value="${esc(loc)}" placeholder="Lagerplats" autocomplete="off"></div><div class="note"><label class="sr-only" for="note-${esc(a.id)}">Anteckning för ${esc(a.nr)}</label><input id="note-${esc(a.id)}" data-field="note" value="${esc(a.note)}" placeholder="Anteckning" autocomplete="off"></div><div class="status-group" role="group" aria-label="Status för ${esc(a.nr)}">${Object.keys(labels).map(s=>`<button class="${s}" data-status="${s}" aria-pressed="${a.status===s}">${s==='found'?'✓ ':s==='notfound'?'✕ ':''}${labels[s]}</button>`).join('')}</div><button class="delete" data-delete title="Ta bort ${esc(a.nr)}" aria-label="Ta bort ${esc(a.nr)}">×</button></div>`}).join('');if(sortBy==='area'&&arr.length){let grouped=new Map();for(const a of arr){let loc=a.location||data.stock[norm(a.nr)]?.location||'',area=loc.match(/^[\p{L}\p{N}]+/u)?.[0]||'Okänd plats';if(!grouped.has(area))grouped.set(area,[]);grouped.get(area).push(a.id)}let nodes=document.createElement('div');nodes.innerHTML=content;let byId=new Map(Array.from(nodes.children).map(n=>[n.dataset.id,n.outerHTML]));content=Array.from(grouped,([area,ids])=>`<div class="areahead">${esc(area)} · ${ids.length}</div>`+ids.map(id=>byId.get(id)||'').join('')).join('')}$('articles').innerHTML=content||'<div class="empty">Inga artiklar matchar.</div>';document.querySelectorAll('.filters button').forEach(b=>b.classList.toggle('selected',b.dataset.filter===filter));}
function renderStock(){let q=norm($('stockSearch').value),list=Object.values(data.stock).filter(x=>norm([x.nr,x.location,x.note,(x.previousLocations||[]).join(' ')].join(' ')).includes(q)).sort((a,b)=>a.nr.localeCompare(b.nr,'sv',{numeric:true}));$('stock').innerHTML=list.map(x=>{let key=norm(x.nr),previous=(x.previousLocations||[]).length?`Tidigare: ${x.previousLocations.join(', ')}`:'Ingen tidigare plats';return `<div class="stockrow" data-key="${esc(key)}"><div><b>${esc(x.nr)}</b><small>${esc(previous)}</small></div><div><label class="sr-only">Lagerplats för ${esc(x.nr)}</label><input data-stock-field="location" value="${esc(x.location)}" placeholder="Lagerplats"></div><div><label class="sr-only">Anteckning för ${esc(x.nr)}</label><input data-stock-field="note" value="${esc(x.note)}" placeholder="Anteckning"></div><div><small>Hittad ${x.foundCount||0} ${(x.foundCount||0)===1?'gång':'gånger'}</small><small>Senast ${date(x.lastSeen||x.updated)}</small><small>${x.lastOrder?'Order '+esc(x.lastOrder):''}</small></div></div>`}).join('')||'<div class="empty">Inga sparade artiklar matchar.</div>';}
function renderCloud(){
 const available=window.Cloud?.available,user=window.Cloud?.user;
 $('loginForm').classList.toggle('hidden',!available||!!user);
 $('codeForm').classList.toggle('hidden',!available||!!user||!cloudEmail);
 $('signOut').classList.toggle('hidden',!user);
 $('syncConflict').classList.toggle('hidden',!cloudConflict);
 $('cloudStatus').textContent=available?(user?`${cloudMessage} · ${user.email||'Inloggad'}`:cloudMessage):'Molnsynk väntar på ett separat Lagerkollen-konto. Lokal backup fungerar fortfarande.';
}
function checkpoint(){try{return JSON.parse(localStorage.getItem(CHECKPOINT)||'null')}catch(e){return null}}
function markSynced(revision){cloudRevision=revision;try{localStorage.setItem(CHECKPOINT,JSON.stringify({userId:Cloud.user.id,localRevision:data._revision,remoteRevision:revision}))}catch(e){}cloudMessage='Synkad';setSaveState('Synkad');renderCloud()}
function replaceFromCloud(row){data=sanitize(row.payload);cloudRevision=row.revision;cloudConflict=null;let raw=JSON.stringify(data);try{localStorage.setItem(KEY,raw)}catch(e){notice('Kunde inte spara molndata lokalt')}writeMirror(raw).catch(()=>{});markSynced(row.revision);render()}
function hasRecords(value){return value.orders.length>0||Object.keys(value.stock).length>0}
function hasLocalData(){return hasRecords(data)}
function shouldSeedCloud(row,cp,userId){return hasLocalData()&&!hasRecords(row.payload)&&(!cp?.userId||cp.userId===userId)}
function showConflict(row){cloudConflict=row;cloudMessage='Synkkonflikt – välj version i Backup & synk';setSaveState('Synkkonflikt',true);renderCloud();notice('Data finns på båda enheterna. Välj version i Backup & synk.')}
async function initCloud(){if(!window.Cloud?.available){renderCloud();return}try{let user=await Cloud.init((event)=>{if(event==='SIGNED_IN')startCloud().catch(syncError);if(event==='SIGNED_OUT'){cloudRevision=null;cloudConflict=null;cloudMessage='Utloggad – data sparas lokalt';renderCloud()}});if(user)await startCloud()}catch(e){syncError(e)}}
function syncError(e){cloudMessage='Synkfel: '+(e.message||e);setSaveState('Synkfel – lokalt sparad',true);renderCloud()}
async function startCloud(){if(!Cloud.user||cloudBusy)return;cloudBusy=true;cloudMessage='Kontrollerar molndata…';renderCloud();try{let row=await Cloud.read(),cp=checkpoint();if(!row){cloudRevision=null;cloudBusy=false;await pushCloud();return}cloudRevision=row.revision;if(shouldSeedCloud(row,cp,Cloud.user.id)){cloudBusy=false;await pushCloud();return}if(!hasLocalData()||(cp?.userId===Cloud.user.id&&cp.localRevision===data._revision)){replaceFromCloud(row)}else{showConflict(row)}}catch(e){syncError(e)}finally{cloudBusy=false}clearInterval(cloudTimer);cloudTimer=setInterval(()=>pullCloud().catch(syncError),15000)}
function scheduleCloudPush(){if(!Cloud?.user||cloudConflict)return;cloudMessage='Ändringar väntar på synk';renderCloud();clearTimeout(pushTimer);pushTimer=setTimeout(()=>pushCloud().catch(syncError),450)}
let pushTimer;
async function pushCloud(){if(!Cloud.user||cloudBusy||cloudConflict)return;cloudBusy=true;const revisionAtStart=data._revision,copy=JSON.parse(JSON.stringify(data));try{let next=await Cloud.write(copy,cloudRevision);if(next===null){let latest=await Cloud.read();if(latest)showConflict(latest);return}cloudRevision=next;if(data._revision===revisionAtStart)markSynced(next);else{try{localStorage.setItem(CHECKPOINT,JSON.stringify({userId:Cloud.user.id,localRevision:revisionAtStart,remoteRevision:next}))}catch(e){}cloudMessage='Fler ändringar väntar'}}catch(e){syncError(e)}finally{cloudBusy=false}if(data._revision!==revisionAtStart&&!cloudConflict)scheduleCloudPush()}
async function pullCloud(){if(!Cloud.user||cloudBusy||cloudConflict||document.hidden)return;let field=document.activeElement;if(field?.closest('.article,.stockrow'))return;cloudBusy=true;try{let row=await Cloud.read();if(!row){cloudRevision=null;cloudBusy=false;await pushCloud();return}if(row.revision===cloudRevision){let cp=checkpoint();if(cp?.localRevision!==data._revision){cloudBusy=false;await pushCloud()}return}let cp=checkpoint();if(cp?.userId===Cloud.user.id&&cp.localRevision===data._revision)replaceFromCloud(row);else showConflict(row)}catch(e){syncError(e)}finally{cloudBusy=false}}
function mergeData(remote,local){let result=sanitize(remote),orders=new Map(result.orders.map(o=>[o.id,o]));for(const incoming of local.orders){let existing=orders.get(incoming.id);if(!existing){orders.set(incoming.id,incoming);continue}let byId=new Map(existing.articles.map(a=>[a.id,a]));for(const article of incoming.articles){let prior=byId.get(article.id);if(!prior||article.updated>prior.updated)byId.set(article.id,article)}existing.deletedArticles={...existing.deletedArticles};for(const [id,time] of Object.entries(incoming.deletedArticles||{}))existing.deletedArticles[id]=Math.max(existing.deletedArticles[id]||0,time);existing.articles=Array.from(byId.values()).filter(a=>a.updated>(existing.deletedArticles[a.id]||0));if(incoming.updated>existing.updated){existing.archived=incoming.archived;existing.updated=incoming.updated}}result.orders=Array.from(orders.values()).sort((a,b)=>b.created-a.created);for(const [key,x] of Object.entries(local.stock)){let prior=result.stock[key];if(!prior||x.updated>prior.updated){result.stock[key]={...x,previousLocations:Array.from(new Set([...(x.previousLocations||[]),...(prior?.previousLocations||[])]))}}else{prior.previousLocations=Array.from(new Set([...(prior.previousLocations||[]),...(x.previousLocations||[])]))}}result.current=local.current||result.current;return result}
function render(){renderOrders();renderOrder();renderStock();renderCloud();$('backupMeta').textContent=`${data.orders.length} ordrar · ${Object.keys(data.stock).length} registerartiklar`;}
$('newOrderToggle').onclick=()=>{$('newOrderForm').classList.toggle('hidden');if(!$('newOrderForm').classList.contains('hidden'))$('orderName').focus()};$('welcomeNew').onclick=startOrder;$('newOrderForm').onsubmit=e=>{e.preventDefault();addOrder($('orderName').value)};
$('orders').onclick=e=>{let b=e.target.closest('[data-order]');if(b)selectOrder(b.dataset.order)};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));$('toggleOrders').onclick=()=>show('orders');$('openBackup').onclick=()=>show('backup');$('stockBack').onclick=$('backupBack').onclick=()=>show('order');
$('archive').onclick=()=>{let o=current();if(!o)return;o.archived=!o.archived;o.updated=Date.now();persist();notice(o.archived?'Order arkiverad':'Order återöppnad')};
$('quickAdd').onclick=()=>{if(addArticles($('quickInput').value))$('quickInput').value='';$('quickInput').focus()};$('quickInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();$('quickAdd').click()}};
$('entryToggle').onclick=()=>{let hidden=$('bulkEntry').classList.toggle('hidden');$('entryToggle').setAttribute('aria-expanded',String(!hidden));if(!hidden)$('paste').focus()};$('add').onclick=()=>{if(addArticles($('paste').value))$('paste').value=''};
$('articleFile').onchange=async e=>{let file=e.target.files?.[0];if(!file)return;try{if(file.size>2e6)throw Error('Filen är för stor (max 2 MB)');let raw=await file.text(),parsed=extract(raw);$('paste').value=raw;$('importPreview').textContent=`${parsed.values.length} möjliga nummer. Granska texten och tryck Lägg till nummer.`;$('bulkEntry').classList.remove('hidden');$('entryToggle').setAttribute('aria-expanded','true')}catch(err){notice(err.message)}e.target.value=''};
$('search').oninput=renderArticles;$('stockSearch').oninput=renderStock;$('sort').onchange=e=>{sortBy=e.target.value;renderArticles()};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;renderArticles()});
$('articles').onclick=e=>{let row=e.target.closest('.article');if(!row)return;let s=e.target.closest('[data-status]');if(s)changeStatus(row.dataset.id,s.dataset.status);if(e.target.closest('[data-delete]'))removeArticle(row.dataset.id)};
$('articles').addEventListener('change',e=>{let row=e.target.closest('.article'),field=e.target.dataset.field;if(row&&['location','note'].includes(field))saveField(row.dataset.id,field,e.target.value)});$('stock').addEventListener('change',e=>{let row=e.target.closest('[data-key]'),field=e.target.dataset.stockField;if(row&&['location','note'].includes(field))updateStock(row.dataset.key,field,e.target.value)});
$('loginForm').onsubmit=async e=>{e.preventDefault();cloudEmail=$('email').value.trim();try{await Cloud.sendLink(cloudEmail);cloudMessage='Kontrollera mejlen och öppna länken på denna enhet. Om mejlet innehåller en kod kan du ange den här.';renderCloud()}catch(err){syncError(err)}};
$('codeForm').onsubmit=async e=>{e.preventDefault();try{await Cloud.verifyCode(cloudEmail||$('email').value.trim(),$('code').value.trim());$('code').value=''}catch(err){syncError(err)}};
$('signOut').onclick=()=>Cloud.signOut().catch(syncError);
$('useCloud').onclick=()=>{if(!cloudConflict)return;if(!confirm('Ersätta denna enhets data med molnversionen? Exportera en backup först om lokala ändringar ska sparas.'))return;replaceFromCloud(cloudConflict)};
$('mergeCloud').onclick=()=>{if(!cloudConflict)return;let merged=mergeData(cloudConflict.payload,data);cloudRevision=cloudConflict.revision;cloudConflict=null;data=merged;persist();notice('Data sammanslagen och synkas till molnet')};
window.addEventListener('online',()=>pullCloud().catch(syncError));document.addEventListener('visibilitychange',()=>{if(!document.hidden)pullCloud().catch(syncError)});
$('export').onclick=()=>{let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='lagerkollen-backup-'+new Date().toISOString().slice(0,10)+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)};
$('import').onchange=async e=>{let file=e.target.files?.[0];if(!file)return;try{if(file.size>20e6)throw Error('Backupen är för stor');let imported=sanitize(JSON.parse(await file.text()));if(confirm(`Ersätta nuvarande data med ${imported.orders.length} ordrar och ${Object.keys(imported.stock).length} registerartiklar? Exportera gärna nuvarande data först.`)){data=imported;persist();show('order');notice('Backup importerad')}}catch(err){notice('Ogiltig backup: '+err.message)}e.target.value=''};
document.addEventListener('keydown',e=>{let typing=e.target.matches('input,textarea,select,[contenteditable]');if(e.key==='Escape'&&e.target===$('search')){$('search').value='';renderArticles();$('search').blur()}if(typing||e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='/'){e.preventDefault();show('order');$('search').focus()}if(e.key.toLowerCase()==='n'){e.preventDefault();show('order');$('quickInput').focus()}});
window.addEventListener('storage',e=>{if(e.key!==KEY||!e.newValue)return;try{let incoming=sanitize(JSON.parse(e.newValue));if(incoming._revision>data._revision){data=incoming;render();notice('Ändringar från en annan flik laddades')}}catch(err){}});
boot();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
