'use strict';
// Jeeves boundary: future authorized adapter should return article/order records to this shape.
// No ERP endpoint or credentials are assumed here.
const JeevesAdapter = Object.freeze({available:false, async lookupArticle(){throw new Error('Jeeves är inte anslutet');}});
const KEY='lagerkollen_v2', DB='lagerkollen-backup', STORE='snapshots', CHECKPOINT='lagerkollen_cloud_checkpoint';
const $=id=>document.getElementById(id);
const LINES=['H1','H2','H3','Elförmontage'];
const blank=()=>({schemaVersion:6,orders:[],sections:LINES.map(name=>({name,updated:0,deleted:false,replacement:''})),groups:[],deletedOrders:{},stock:{},current:null});
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const date=t=>t?new Date(t).toLocaleString('sv-SE',{dateStyle:'short',timeStyle:'short'}):'–';
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,9);
const norm=s=>String(s||'').trim().toUpperCase();
const labels={neutral:'Neutral',fetched:'Hämtad',notfound:'Inte hittad',found:'Hittad, ej hämtad'};
const statusLabel=status=>labels[status]||labels.neutral;
function normalizePicklist(order){return order;}
const optionalNumber=value=>value==null||value===''?null:Number.isFinite(Number(value))&&Number(value)>=0?Number(value):null;
const quantity=value=>value==null?'—':Number(value).toLocaleString('sv-SE',{maximumFractionDigits:3});
function sanitizeArticle(a){let modern=a.statusVersion===2||['neutral','fetched'].includes(a.status),previous=a.previousStatus;return {id:String(a.id||uid()),nr:String(a.nr),description:String(a.description||''),status:modern&&labels[a.status]?a.status:'neutral',statusVersion:2,blockReason:String(a.blockReason||'').slice(0,1000),previousStatus:previous&&typeof previous==='object'?{status:String(previous.status||''),updated:Number(previous.updated)||0}:!modern&&a.status?{status:String(a.status),updated:Number(a.updated)||0}:null,location:String(a.location||''),note:String(a.note||''),updated:Number(a.updated)||Date.now(),isGroup:!!a.isGroup,requiredQty:optionalNumber(a.requiredQty),perUnitQty:optionalNumber(a.perUnitQty),availableQty:optionalNumber(a.availableQty),shortageQty:optionalNumber(a.shortageQty),unit:String(a.unit||'')};}
function mergeArticle(prior,incoming){if(!prior)return incoming;let result={...prior,...incoming,description:incoming.description||prior.description,isGroup:!!(prior.isGroup||incoming.isGroup),unit:incoming.unit||prior.unit};for(const key of ['requiredQty','perUnitQty','availableQty','shortageQty'])result[key]=incoming[key]??prior[key]??null;return result;}
function spreadsheetCell(value,preserveNumber=false){let cell=String(value??'').replace(/[\t\r\n]+/g,' ').trim();return /^[=+\-@]/.test(cell)||(preserveNumber&&/^0\d/.test(cell))?"'"+cell:cell;}
function formatOrderResults(order){let rows=[['Order','Artikelnummer','Benämning','Status','Lagerplats','Behov','Enhet','Per aggregat','Finns VBA1','Saknas VBA1','Anteckning','Hämtningshinder'].join('\t')];for(const a of order.articles.filter(a=>!a.isGroup)){rows.push([spreadsheetCell(order.name,true),spreadsheetCell(a.nr,true),spreadsheetCell(a.description),statusLabel(a.status,order),spreadsheetCell(a.location),a.requiredQty==null?'':quantity(a.requiredQty),spreadsheetCell(a.unit),a.perUnitQty==null?'':quantity(a.perUnitQty),a.availableQty==null?'':quantity(a.availableQty),a.shortageQty==null?'':quantity(a.shortageQty),spreadsheetCell(a.note),spreadsheetCell(a.blockReason)].join('\t'))}return rows.join('\n');}
async function copyText(value){if(navigator.clipboard?.writeText){try{await navigator.clipboard.writeText(value);return}catch(e){}}let previous=document.activeElement,field=document.createElement('textarea');field.value=value;field.style.cssText='position:fixed;left:-9999px;top:0';document.body.append(field);field.focus();field.select();let copied=document.execCommand('copy');field.remove();previous?.focus?.();if(!copied)throw new Error('Kopiering stöds inte här');}
let data=blank(), view='order', filter='all', sortBy='default', sectionFilter='', toastTimer, dbPromise;
let cloudRevision=null, cloudBusy=false, cloudConflict=null, cloudTimer, cloudMessage='Logga in för synk mellan mobil och dator', cloudEmail='';
function sanitize(input){
 if(!input||!Array.isArray(input.orders)||!input.stock||typeof input.stock!=='object'||Array.isArray(input.stock))throw new Error('Ogiltig data');
 if(Number(input.schemaVersion)>6)throw new Error('Den här datan kräver en nyare version. Uppdatera sidan.');
 const out=blank();out._revision=Number(input._revision)||0;
 out.deletedOrders=Object.fromEntries(Object.entries(input.deletedOrders||{}).filter(([id,time])=>id&&Number.isFinite(Number(time))&&Number(time)>0).map(([id,time])=>[id,Number(time)]));
 out.sections=mergeSections([],Array.isArray(input.sections)?input.sections:out.sections);
 out.groups=mergeGroups([],Array.isArray(input.groups)?input.groups:[]);
 out.orders=input.orders.filter(o=>o&&typeof o==='object').map(o=>({id:String(o.id||uid()),name:String(o.name||'Namnlös'),created:Number(o.created)||Date.now(),updated:Number(o.updated)||Number(o.created)||Date.now(),archived:!!o.archived,line:String(o.line||'').trim().slice(0,80),subgroup:String(o.subgroup||'').trim().slice(0,80),kind:o.kind==='picklist'?'picklist':'shortage',productName:String(o.productName||''),productNr:String(o.productNr||''),productionQty:optionalNumber(o.productionQty),printedAt:String(o.printedAt||''),deletedArticles:Object.fromEntries(Object.entries(o.deletedArticles||{}).filter(([id,time])=>id&&Number.isFinite(Number(time))&&Number(time)>0).map(([id,time])=>[id,Number(time)])),articles:(Array.isArray(o.articles)?o.articles:[]).filter(a=>a&&a.nr).map(sanitizeArticle)}));
 out.orders=out.orders.filter(o=>!Object.hasOwn(out.deletedOrders,o.id));out.orders.forEach(normalizePicklist);
 for(const o of out.orders)if((Number(input.schemaVersion)||0)<5&&o.line&&o.subgroup&&!out.groups.some(g=>groupKey(g)===groupKey({line:o.line,name:o.subgroup})))out.groups=mergeGroups(out.groups,[{line:o.line,name:o.subgroup,updated:o.updated}]);
 for(const [key,x] of Object.entries(input.stock)){if(!x||typeof x!=='object')continue;const k=norm(key||x.nr);if(!k)continue;out.stock[k]={nr:String(x.nr||key),description:String(x.description||''),location:String(x.location||''),locationUpdated:Number(x.locationUpdated)||Number(x.updated)||0,locationOrder:String(x.locationOrder||x.lastOrder||''),updated:Number(x.updated)||0,previousLocations:Array.isArray(x.previousLocations)?x.previousLocations.filter(v=>typeof v==='string').slice(0,20):[],lastSeen:Number(x.lastSeen)||0,lastFoundLocation:String(x.lastFoundLocation||((x.lastSeen&&x.location)||'')),foundCount:Number(x.foundCount)||0,lastOrder:String(x.lastOrder||''),note:String(x.note||'')};}
 out.current=out.orders.some(o=>o.id===input.current)?input.current:(out.orders.find(o=>!o.archived)||out.orders[0]||{}).id||null;
 reconcilePlacement(out);return out;
}
function db(){if(!('indexedDB'in window))return Promise.reject(Error('IndexedDB saknas'));if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return dbPromise;}
async function readMirror(){let d=await db();return new Promise((resolve,reject)=>{let r=d.transaction(STORE).objectStore(STORE).get('current');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});}
async function writeMirror(value){let d=await db();return new Promise((resolve,reject)=>{let tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).put(value,'current');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});}
function notice(message){let el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3500)}
function setSaveState(message,issue=false){$('saveState').textContent=message;$('saveState').style.color=issue?'#ffd3a3':'';}
function persist(renderUI=true){data._revision=Math.max(Date.now(),(data._revision||0)+1);let value=JSON.stringify(data),localOK=true;try{localStorage.setItem(KEY,value);setSaveState('Sparad lokalt')}catch(e){localOK=false;setSaveState('Lagring misslyckades',true);notice('Kunde inte spara lokalt. Exportera en backup nu.')}writeMirror(value).then(()=>{if(!localOK)setSaveState('Reservkopia sparad',true)}).catch(()=>{if(!localOK)notice('Ingen lokal lagring fungerar. Exportera nu.')});if(renderUI)render();scheduleCloudPush();}
async function boot(){let local=null,mirror=null;try{let raw=localStorage.getItem(KEY);if(raw)local=sanitize(JSON.parse(raw))}catch(e){setSaveState('Lagring kunde inte läsas',true)}try{let raw=await readMirror();if(raw)mirror=sanitize(JSON.parse(raw))}catch(e){}data=mirror&&(!local||mirror._revision>local._revision)?mirror:(local||blank());if(mirror&&mirror===data&&!local){try{localStorage.setItem(KEY,JSON.stringify(data))}catch(e){}notice('Lokal reservkopia återställd')}render();await initCloud();}
function current(){return data.orders.find(o=>o.id===data.current)}
function selectOrder(id){if(!data.orders.some(o=>o.id===id))return;data.current=id;sectionFilter='';filter='all';$('search').value='';try{localStorage.setItem(KEY,JSON.stringify(data))}catch(e){}writeMirror(JSON.stringify(data)).catch(()=>{});show('order');}
function show(next){view=next;let mobileOrders=next==='orders';$('sidebar').classList.toggle('open',mobileOrders);$('orderView').classList.toggle('hidden',next==='stock'||next==='backup'||next==='edit'||mobileOrders);$('stockView').classList.toggle('hidden',next!=='stock');$('backupView').classList.toggle('hidden',next!=='backup');$('editView').classList.toggle('hidden',next!=='edit');document.querySelectorAll('.mobile-nav button').forEach(b=>b.classList.toggle('selected',b.dataset.view===next));if(next==='stock')$('stockSearch').focus();render();}
function startOrder(){show('orders');$('newOrderForm').classList.remove('hidden');$('orderName').focus();refreshGroupChoices();}
function headingName(name){return String(name||'').trim().slice(0,80);}
function mergeHeadingRecords(a,b,key){let records=new Map();for(const r of [...a,...b]){if(!r||!headingName(r.name)||(key===groupKey&&!headingName(r.line)))continue;let x={name:headingName(r.name),updated:Number(r.updated)||0,deleted:!!r.deleted,replacement:headingName(r.replacement)};if(key===groupKey)x.line=headingName(r.line);let id=key(x),old=records.get(id);if(!old||x.updated>old.updated||(x.updated===old.updated&&x.deleted&&!old.deleted))records.set(id,x);}return Array.from(records.values());}
function groupKey(g){return JSON.stringify([norm(g.line),norm(g.name)]);}
function mergeSections(a,b){return mergeHeadingRecords(a,b,g=>norm(g.name));}
function mergeGroups(a,b){return mergeHeadingRecords(a,b,groupKey);}
function lineNames(value=data){return (value.sections||[]).filter(x=>!x.deleted).map(x=>x.name);}
function activeGroups(line,value=data){return (value.groups||[]).filter(g=>!g.deleted&&norm(g.line)===norm(line));}
function resolveHeading(records,name){let seen=new Set();while(name&&!seen.has(norm(name))){seen.add(norm(name));let r=records.find(r=>norm(r.name)===norm(name));if(!r)return '';if(!r.deleted)return r.name;name=r.replacement;}return '';}
function reconcilePlacement(value){for(const o of value.orders){if(!o.line){o.subgroup='';continue;}o.line=resolveHeading(value.sections,o.line);o.subgroup=o.line?resolveHeading(value.groups.filter(g=>norm(g.line)===norm(o.line)),o.subgroup):'';}return value;}
function headingTime(){return Math.max(Date.now(),...data.sections.map(x=>x.updated+1),...data.groups.map(x=>x.updated+1));}
function ensureGroup(line,name){name=headingName(name);line=lineNames().find(x=>norm(x)===norm(line));if(!line||!name)return '';let prior=activeGroups(line).find(g=>norm(g.name)===norm(name));if(prior)return prior.name;data.groups=mergeGroups(data.groups,[{line,name,updated:headingTime()}]);return name;}
function addSection(name){name=headingName(name);if(!name)return false;if(norm(name)==='SHORTAGE'||norm(name)==='SAKNADE ARTIKLAR'){notice('Saknade artiklar finns redan som separat lista.');return false;}if(lineNames().some(x=>norm(x)===norm(name))){notice('Sektionen finns redan.');return false;}data.sections=mergeSections(data.sections,[{name,updated:headingTime()}]);persist();notice('Sektion tillagd');return true;}
function renameHeading(line,name,next){next=headingName(next);if(!next)return false;let section=!name,old=section?line:name,records=section?data.sections:data.groups.filter(g=>norm(g.line)===norm(line));if(!records.some(r=>!r.deleted&&norm(r.name)===norm(old)))return false;if(norm(next)==='SHORTAGE'||norm(next)==='SAKNADE ARTIKLAR'){notice('Det namnet används för bristlistor.');return false;}if(records.some(r=>!r.deleted&&norm(r.name)===norm(next)&&norm(r.name)!==norm(old))){notice('Namnet finns redan. Välj ett annat.');return false;}let time=headingTime(),same=norm(old)===norm(next),changes=[{name:next,line,updated:time}];if(!same)changes.unshift({name:old,line,updated:time,deleted:true,replacement:next});if(section){data.sections=mergeSections(data.sections,changes);let groups=data.groups.filter(g=>norm(g.line)===norm(line));for(const g of groups)data.groups=mergeGroups(data.groups,[...(!same?[{...g,updated:time,deleted:true,replacement:''}]:[]),{...g,line:next,updated:time}]);for(const o of data.orders)if(norm(o.line)===norm(line)){o.line=next;o.updated=time;}}else{data.groups=mergeGroups(data.groups,changes);for(const o of data.orders)if(norm(o.line)===norm(line)&&norm(o.subgroup)===norm(old)){o.subgroup=next;o.updated=time;}}reconcilePlacement(data);persist();notice('Namnet uppdaterat');return true;}
function deleteHeading(line,name=''){let section=!name,old=section?line:name,records=section?data.sections:data.groups.filter(g=>norm(g.line)===norm(line));if(!records.some(r=>!r.deleted&&norm(r.name)===norm(old)))return false;if(!confirm('Ta bort '+(section?'sektionen ':'underrubriken ')+old+'?\nOrdrarna och artiklarna behålls. '+(section?'Ordrarna flyttas till Ej placerade.':'Ordrarna ligger kvar direkt under '+line+'.')))return false;let time=headingTime(),record={name:old,line,updated:time,deleted:true};if(section){data.sections=mergeSections(data.sections,[record]);data.groups=mergeGroups(data.groups,data.groups.filter(g=>norm(g.line)===norm(line)).map(g=>({...g,updated:time,deleted:true,replacement:''})));}else data.groups=mergeGroups(data.groups,[record]);reconcilePlacement(data);persist();notice('Rubrik borttagen. Ordrarna är kvar.');return true;}
function groupOptions(line){return activeGroups(line).map(g=>'<option value="'+esc(g.name)+'">'+esc(g.name)+'</option>').join('');}
function fillGroupSelect(id,line,value=''){let el=$(id),groups=activeGroups(line),valid=lineNames().includes(line);el.innerHTML='<option value="">'+(valid?(groups.length?'Utan underrubrik':'Inga underrubriker – se Redigera'):'Välj produktionslinje först')+'</option>'+groupOptions(line);el.disabled=!valid||!groups.length;el.value=groups.find(g=>norm(g.name)===norm(value))?.name||'';}
function configuredGroup(line,name){return activeGroups(line).find(g=>norm(g.name)===norm(name))?.name||'';}
function refreshLineChoices(){for(const [id,first,extra] of [['orderLine','Välj…','<option value="shortage">Saknade artiklar</option>'],['placementLine','Ej placerad','']]){let el=$(id),value=el.value;el.innerHTML='<option value="">'+first+'</option>'+lineNames().map(name=>'<option value="'+esc(name)+'">'+esc(name)+'</option>').join('')+extra;el.value=value;}refreshGroupChoices();}
function renderEditor(){let actions=(line,name='')=>'<div class="heading-actions"><button class="secondary small" type="button" data-rename-heading="'+esc(line)+'" data-heading-name="'+esc(name)+'" aria-label="Byt namn på '+esc(name||line)+'">Byt namn</button><button class="secondary small danger" type="button" data-delete-heading="'+esc(line)+'" data-heading-name="'+esc(name)+'" aria-label="Ta bort '+esc(name||line)+'">Ta bort</button></div>';$('headingEditor').innerHTML=lineNames().map((line,index)=>'<section class="panel heading-panel"><div class="heading-row"><h3>'+esc(line)+'</h3>'+actions(line)+'</div><div class="heading-groups">'+activeGroups(line).map(g=>'<div class="heading-row"><strong>'+esc(g.name)+'</strong>'+actions(line,g.name)+'</div>').join('')+'</div><form class="heading-add" data-add-heading="'+esc(line)+'"><label class="sr-only" for="group-'+index+'">Ny underrubrik i '+esc(line)+'</label><input id="group-'+index+'" name="heading" placeholder="Ny underrubrik, t.ex. Cup" maxlength="80" required><button class="primary" type="submit">Lägg till underrubrik</button></form></section>').join('')||'<div class="empty">Inga sektioner ännu. Lägg till din första ovan.</div>';}
function refreshGroupChoices(){let line=$('orderLine').value;$('newGroupField').classList.toggle('hidden',line==='shortage');$('orderName').required=line!=='shortage';$('orderName').placeholder=line==='shortage'?'Valfritt listnamn':'T.ex. 112949';fillGroupSelect('orderGroup',line,$('orderGroup').value);$('orderGroupHint').textContent=lineNames().includes(line)&&!activeGroups(line).length?'Lägg till underrubriker för '+line+' på Redigera, eller skapa ordern utan underrubrik.':'Underrubriker hanteras på Redigera.';}
function addOrder(name,line='',subgroup='',productName=''){name=name.trim()||(line==='shortage'?'Saknade artiklar':'');if(!name)return;let kind=line==='shortage'?'shortage':'picklist';line=lineNames().includes(line)?line:'';if(kind==='picklist'&&subgroup&&!configuredGroup(line,subgroup)){notice('Välj en befintlig underrubrik. Lägg till nya på Redigera.');return;}subgroup=kind==='picklist'?configuredGroup(line,subgroup):'';let o={id:uid(),name,kind,line,subgroup,productName:String(productName||'').trim(),created:Date.now(),updated:Date.now(),archived:false,articles:[]};data.orders.unshift(o);data.current=o.id;$('orderName').value='';$('newOrderForm').reset?.();$('newOrderForm').classList.add('hidden');persist();show('order');$('quickInput').focus();}
function freshPickingOrder(source,name,productionQty=source.productionQty){let now=Math.max(Date.now(),(source.updated||0)+1),qty=optionalNumber(productionQty);return {...source,id:uid(),name:String(name||source.name).trim(),created:now,updated:now,archived:false,productionQty:qty,printedAt:'',deletedArticles:{},articles:source.articles.map(a=>{let stock=data.stock[norm(a.nr)],required=a.requiredQty;if(!a.isGroup&&qty!==source.productionQty)required=a.perUnitQty!=null&&qty!=null?a.perUnitQty*qty:source.productionQty>0&&qty!=null&&a.requiredQty!=null?a.requiredQty*qty/source.productionQty:null;return {...a,id:uid(),status:'neutral',statusVersion:2,previousStatus:null,blockReason:'',note:'',location:a.isGroup?'':stock?.location||a.location||'',requiredQty:required,availableQty:null,shortageQty:null,updated:now};})};}
function repeatOrder(name,productionQty){let source=current();if(!source?.articles.some(a=>!a.isGroup)||!String(name||'').trim())return false;let next=freshPickingOrder(source,name,productionQty);source.archived=true;source.updated=next.updated;data.orders.unshift(next);data.current=next.id;filter='all';sectionFilter='';sortBy='default';$('search').value='';$('sort').value='default';persist();show('order');notice('Ny plockomgång skapad. Den förra finns i historiken.');return true;}
function removeOrder(id){let o=data.orders.find(o=>o.id===id);if(!o)return;if(!confirm('Radera order '+o.name+' helt?\nOrdern och dess artikelrader tas bort från alla synkade enheter. Sparade lagerplatser i lagerregistret behålls.'))return;data.deletedOrders={...(data.deletedOrders||{}),[id]:Date.now()};data.orders=data.orders.filter(o=>o.id!==id);if(data.current===id)data.current=(data.orders.find(o=>!o.archived)||data.orders[0]||{}).id||null;persist();notice('Order raderad. Lagerregistret är kvar.');}
function placeOrder(line,subgroup){let o=current();if(!o||o.kind==='shortage')return;if(subgroup&&!configuredGroup(line,subgroup)){notice('Välj en befintlig underrubrik. Lägg till nya på Redigera.');return;}o.line=lineNames().includes(line)?line:'';o.subgroup=o.line?configuredGroup(o.line,subgroup):'';o.updated=Date.now();persist();notice('Orderns placering sparad');}
function extract(raw){let values=[],ignored=0,lines=raw.split(/\r?\n/),csvHeader=lines.some(line=>/^(artikel(nummer|nr)?|article|item|sku)([,;\t]|$)/i.test(line.trim()));for(const line of lines){let s=line.trim();if(!s)continue;if(/^(artikel(nummer|nr)?|article|item|sku|antal|quantity)\b/i.test(s)){ignored++;continue}let cells=s.includes('\t')?s.split('\t'):s.includes(';')?s.split(';'):csvHeader&&s.includes(',')?s.split(','):null;let tokens;if(cells&&cells.length>1){tokens=[cells[0]]}else{tokens=s.split(/[\s,;]+/)}for(let token of tokens){token=token.replace(/^["'“”\[({]+|["'“”\])}.]+$/g,'').trim();if(!/^[\p{L}\p{N}][\p{L}\p{N}._\/-]*$/u.test(token)||token.length<2||token.length>48){ignored++;continue}values.push(token)}}return {values,ignored};}
function addArticles(raw){let o=current();if(!o)return;let parsed=extract(raw),seen=new Set(o.articles.map(a=>norm(a.nr))),added=0,duplicate=0;for(const nr of parsed.values){let key=norm(nr);if(seen.has(key)){duplicate++;continue}seen.add(key);let old=data.stock[key]||{};o.articles.push(sanitizeArticle({id:uid(),nr,description:old.description||'',status:'neutral',statusVersion:2,location:old.location||'',note:'',updated:Date.now()}));added++}if(added){o.updated=Date.now();persist()}notice(`${added} tillagda${duplicate?` · ${duplicate} dubbletter hoppades över`:''}${parsed.ignored?` · ${parsed.ignored} ogiltiga rader`:''}`);return added;}
function saveField(id,field,value){let a=current()?.articles.find(a=>a.id===id);if(!a||a.isGroup)return;value=String(value).trim();if(a[field]===value)return;a[field]=value;a.updated=Date.now();current().updated=a.updated;rememberArticle(a,current(),field==='location',field==='note');persist(false);let row=Array.from(document.querySelectorAll('.article')).find(el=>el.dataset.id===id);if(row?.querySelector('.context'))row.querySelector('.context').textContent=articleContext(a);}
function rememberArticle(a,o,saveLocation=false,saveNote=false){let k=norm(a.nr),x=data.stock[k]||{nr:a.nr,description:'',location:'',locationUpdated:0,locationOrder:'',updated:0,previousLocations:[],lastSeen:0,lastFoundLocation:'',foundCount:0,lastOrder:'',note:''};if(a.description)x.description=a.description;if(saveLocation&&a.location){let previous=String(x.location||'').trim(),next=a.location.trim();if(previous&&norm(previous)!==norm(next))x.previousLocations=[previous,...(x.previousLocations||[]).filter(p=>norm(p)!==norm(previous)&&norm(p)!==norm(next))].slice(0,20);x.location=next;x.locationUpdated=Date.now();x.locationOrder=o.name;}if(saveNote||a.note)x.note=a.note;x.updated=Date.now();data.stock[k]=x;return x;}
function rememberFound(a,o,increment){let x=rememberArticle(a,o,!!a.location);x.lastSeen=Date.now();x.lastFoundLocation=a.location||'';x.lastOrder=o.name;if(increment)x.foundCount=(x.foundCount||0)+1;}
let pendingFound=null;
function changeStatus(id,status,reason){let o=current(),a=o?.articles.find(a=>a.id===id);if(!a||a.isGroup||!labels[status])return false;if(status==='found'){if(reason===undefined){pendingFound={orderId:o.id,articleId:id};$('foundReason').value=a.blockReason||'';$('foundArticle').textContent=a.nr;$('foundDialog').showModal();$('foundReason').focus();return false;}reason=String(reason).trim().slice(0,1000);if(!reason){notice('Ange varför artikeln inte kan hämtas.');return false;}a.blockReason=reason;}let was=a.status;a.status=status;a.statusVersion=2;a.updated=Date.now();o.updated=a.updated;if(['found','fetched'].includes(status)&&!['found','fetched'].includes(was))rememberFound(a,o,true);persist();return true;}
function removeArticle(id){let o=current(),a=o?.articles.find(a=>a.id===id);if(!a||!confirm(`Ta bort ${a.nr} från ordern?`))return;o.articles=o.articles.filter(x=>x.id!==id);o.updated=Date.now();(o.deletedArticles??={})[id]=o.updated;persist();}
function updateStock(key,field,value){let x=data.stock[key];if(!x)return;value=value.trim();if(field==='location'&&x.location&&norm(x.location)!==norm(value))x.previousLocations=[x.location,...(x.previousLocations||[]).filter(p=>norm(p)!==norm(x.location))].slice(0,20);x[field]=value;x.updated=Date.now();if(field==='location'){x.locationUpdated=x.updated;x.locationOrder=''}persist(false);}
function orderRows(list){return list.map(o=>{let materials=o.articles.filter(a=>!a.isGroup),missing=materials.filter(a=>a.status==='notfound').length;return '<button class="order-row '+(o.id===data.current?'selected':'')+'" data-order="'+esc(o.id)+'"><span class="line"><strong>'+esc(o.name)+'</strong><span class="count '+(missing?'has-missing':'no-missing')+'">'+missing+' saknas</span></span><small>'+(o.productName?esc(o.productName)+' · ':'')+materials.length+' artiklar · '+date(o.created)+'</small></button>';}).join('');}
function renderOrderSections(){
 let active=data.orders.filter(o=>!o.archived),past=data.orders.filter(o=>o.archived),html='';
 for(const line of lineNames()){let orders=active.filter(o=>o.kind==='picklist'&&o.line===line),names=Array.from(new Map([...activeGroups(line).map(g=>g.name),...orders.map(o=>o.subgroup).filter(Boolean)].map(name=>[norm(name),name])).values());html+='<section class="line-section production-section" aria-label="'+esc(line)+'"><div class="line-section-head"><div class="line-title"><span class="section-label">PRODUKTIONSLINJE</span><h3>'+esc(line)+' <span>'+orders.length+'</span></h3></div><button type="button" class="add-subgroup" data-add-group="'+esc(line)+'" aria-label="Ny underrubrik i '+esc(line)+'">+ Typ</button></div><div class="line-content">'+orderRows(orders.filter(o=>!o.subgroup));for(const name of names){let list=orders.filter(o=>norm(o.subgroup)===norm(name));html+='<section class="subgroup-block" aria-label="'+esc(line)+' – '+esc(name)+'"><div class="subgroup-heading"><div><span class="subgroup-label">AGGREGATTYP</span><h4>'+esc(name)+'</h4></div><span>'+list.length+'</span><button type="button" data-new-in-line="'+esc(line)+'" data-new-in-group="'+esc(name)+'" aria-label="Skapa order i '+esc(name)+'">+ Order</button></div>'+orderRows(list)+(list.length?'':'<p class="subgroup-empty">Inga aktiva ordrar</p>')+'</section>';}if(!orders.length&&!names.length)html+='<p class="section-empty">Inga aktiva ordrar</p>';html+='</div></section>';}
 let unplaced=active.filter(o=>o.kind==='picklist'&&!o.line);if(unplaced.length)html+='<section class="line-section"><div class="order-section">Ej placerade · '+unplaced.length+'</div>'+orderRows(unplaced)+'</section>';
 let shortages=active.filter(o=>o.kind==='shortage');html+='<section class="line-section"><div class="order-section">Saknade artiklar · '+shortages.length+'</div>'+orderRows(shortages)+(shortages.length?'':'<p class="section-empty">Inga listor ännu</p>')+'</section>';
 if(past.length)html+='<section class="line-section"><div class="order-section">Historik · '+past.length+'</div>'+orderRows(past)+'</section>';
 return html;
}
function renderOrders(){$('orders').innerHTML=renderOrderSections();$('stockCount').textContent=Object.keys(data.stock).length;document.querySelectorAll('[data-view]').forEach(b=>{let selected=b.dataset.view===view||(b.dataset.view==='order'&&view==='orders'&&!!b.closest('.desktop-nav'));b.classList.toggle('selected',selected);if(selected)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});if(typeof renderWorkbenchOrders==='function')renderWorkbenchOrders();}
function articleSections(order){let sections=[],members=new Map(),key='ungrouped';for(const a of order.articles){if(a.isGroup){key=a.id;sections.push({key,name:a.description||a.nr,count:0});}else{members.set(a.id,key);let section=sections.find(s=>s.key===key);if(!section){section={key,name:'Utan sektionsrubrik',count:0};sections.push(section);}section.count++;}}return {sections:sections.filter(s=>s.count),members};}
function sectionOrder(order){if(!sectionFilter)return order;let {members}=articleSections(order);return {...order,articles:order.articles.filter(a=>a.isGroup?a.id===sectionFilter:members.get(a.id)===sectionFilter)};}
function renderSectionChoices(order){let {sections}=articleSections(order);if(!sections.some(s=>s.key===sectionFilter))sectionFilter='';let el=$('articleSection');el.innerHTML='<option value="">Alla sektioner</option>'+sections.map(s=>'<option value="'+esc(s.key)+'">'+esc(s.name)+' · '+s.count+'</option>').join('');el.value=sectionFilter;el.disabled=!order.articles.some(a=>a.isGroup);let total=order.articles.filter(a=>!a.isGroup).length,shown=sectionOrder(order).articles.filter(a=>!a.isGroup).length;$('sectionScope').textContent=sectionFilter?'Visar '+shown+' av '+total+' artiklar · räknare och översikter gäller vald sektion':el.disabled?'Inga sektionsrubriker i denna order':'Visa hela ordern eller välj en sektion från plocklistan';}
function renderOrder(){
 let o=current();$('noActive').classList.toggle('hidden',!!o);$('activeWrap').classList.toggle('hidden',!o);if(!o)return;
 $('placementForm').classList.toggle('hidden',o.kind==='shortage');$('placementLine').value=o.line||'';fillGroupSelect('placementGroup',o.line,o.subgroup);
 renderSectionChoices(o);let scoped=sectionOrder(o),articles=scoped.articles.filter(a=>!a.isGroup);$('repeatOrder').disabled=!o.articles.some(a=>!a.isGroup);$('orderEyebrow').textContent=o.archived?'ARKIVERAD ORDER':o.kind==='picklist'?'PLOCKLISTA':'AKTIV ORDER';$('activeTitle').textContent=`Order ${o.name}`;
 $('activeMeta').textContent=[o.line,o.subgroup,o.productName,o.productNr?'Produkt '+o.productNr:'',o.productionQty!=null?quantity(o.productionQty)+' aggregat':'',o.archived?'Arkiverad':'Pågående','Omgång '+date(o.created)].filter(Boolean).join(' · ')||`Skapad ${date(o.created)}`;
 $('sourceInfo').classList.toggle('hidden',!o.printedAt);$('sourceInfo').textContent=`Mängder enligt plocklistan ${o.printedAt}. VBA1 är produktionsplatsen. Lagerplatsen nedan är platsen att hämta från.`;
 $('archive').textContent=o.archived?'Återöppna':'Arkivera';$('copyResults').disabled=!articles.length;$('tot').textContent=articles.length;$('missingLabel').textContent='Neutrala';
 document.querySelector('.stat-missing').classList.remove('hidden');
 document.querySelector('.stat-notfound span').textContent='Inte hittade';

 document.querySelector('.filters [data-filter="notfound"]').textContent=statusLabel('notfound',o);
 for(const [id,status] of [['mis','neutral'],['fnd','found'],['nf','notfound'],['fetched','fetched']])$(id).textContent=articles.filter(a=>a.status===status).length;$('missingOverview').innerHTML=missingOverview(scoped)+blockedOverview(scoped);renderArticles();
}
function missingOverview(order){
 const articles=order.articles.filter(a=>!a.isGroup&&a.status==='notfound');
 const head=`<div class="missing-overview-head"><div><span class="eyebrow">ORDER ${esc(order.name)}</span><h3 id="missingOverviewTitle">Saknas <span class="missing-total">${articles.length}</span></h3></div><span class="missing-overview-caption">${order.kind==='shortage'?'Artiklar som saknas':'Markerade som inte hittade'}</span></div>`;
 if(!articles.length)return head+'<p class="missing-overview-empty">Inga artiklar markerade som inte hittade.</p>';
 return head+`<table class="missing-table"><thead><tr><th scope="col">Artikelnummer</th><th scope="col">Benämning</th><th scope="col">Behov</th><th scope="col">Status</th></tr></thead><tbody>${articles.map(a=>`<tr><th scope="row">${esc(a.nr)}</th><td class="missing-description">${esc(a.description||data.stock[norm(a.nr)]?.description||'Benämning saknas')}</td><td class="missing-quantity"><span class="mobile-quantity-label">Behov </span>${a.requiredQty==null?'—':`${quantity(a.requiredQty)} ${esc(a.unit)}`}</td><td class="missing-state"><span class="missing-badge"><span aria-hidden="true">!</span> Saknas</span></td></tr>`).join('')}</tbody></table><p class="missing-overview-footnote">Behov är orderns totala mängd enligt plocklistan.</p>`;
}
function blockedOverview(order){let articles=order.articles.filter(a=>!a.isGroup&&a.status==='found');if(!articles.length)return '';return '<section class="blocked-overview"><h3>Hittade, ej hämtade · '+articles.length+'</h3><div class="blocked-list">'+articles.map(a=>'<div><strong>'+esc(a.nr)+'</strong><span>'+esc(a.description)+'</span><p>'+esc(a.blockReason||'Anmärkning saknas')+'</p></div>').join('')+'</div></section>';}
function articleContext(a){let old=data.stock[norm(a.nr)]||{},parts=[];if(old.location){parts.push(`Senast känd: ${old.location}`);if(old.locationUpdated)parts.push(date(old.locationUpdated));}else parts.push('Ingen sparad lagerplats');if(old.previousLocations?.length)parts.push('Tidigare: '+old.previousLocations.join(', '));if(old.lastSeen)parts.push('Senast hittad '+date(old.lastSeen));return parts.join(' · ');}
function renderArticle(a,o){
 if(a.isGroup)return `<div class="article-group"><strong>${esc(a.nr)}</strong> ${esc(a.description)} <small>Grupprubrik · inget materialbehov</small></div>`;
 let old=data.stock[norm(a.nr)]||{},description=a.description||old.description||'';
 let quantities=a.requiredQty==null?'':`<div class="quantities"><span>Behov <b>${quantity(a.requiredQty)} ${esc(a.unit)}</b></span><span>Per aggregat <b>${quantity(a.perUnitQty)} ${esc(a.unit)}</b></span><span>Finns VBA1 <b>${quantity(a.availableQty)} ${esc(a.unit)}</b></span><span class="${a.shortageQty>0?'shortage':''}">Saknas VBA1 <b>${quantity(a.shortageQty)} ${a.shortageQty==null?'':esc(a.unit)}</b></span></div>`;
 return `<div class="article ${a.status}" data-id="${esc(a.id)}"><div class="identity"><div class="number">${esc(a.nr)}</div>${description?`<div class="description">${esc(description)}</div>`:''}<div class="context">${esc(articleContext(a))}</div></div><div class="location"><label class="sr-only" for="loc-${esc(a.id)}">Lagerplats för ${esc(a.nr)}</label><input id="loc-${esc(a.id)}" data-field="location" value="${esc(a.location)}" placeholder="Hämta från lagerplats" autocomplete="off" autocapitalize="characters">${!a.location&&old.location?`<button class="use-known" data-use-known>Använd ${esc(old.location)}</button>`:''}</div><div class="note"><label class="sr-only" for="note-${esc(a.id)}">Anteckning för ${esc(a.nr)}</label><input id="note-${esc(a.id)}" data-field="note" value="${esc(a.note)}" placeholder="Anteckning" autocomplete="off"></div><div class="status-group ${o.kind==='picklist'?'picklist-status':''}" role="group" aria-label="Status för ${esc(a.nr)}">${Object.keys(labels).map(status=>`<button class="${status}" data-status="${status}" aria-pressed="${a.status===status}">${status==='fetched'?'✓ ':status==='notfound'?'✕ ':status==='found'?'◉ ':'— '}${statusLabel(status,o)}</button>`).join('')}</div><button class="delete" data-delete title="Ta bort ${esc(a.nr)}" aria-label="Ta bort ${esc(a.nr)}">×</button>${quantities}${a.status==='found'?'<div class="blocking-reason"><strong>Kan inte hämtas:</strong> '+esc(a.blockReason||'Ange anmärkning')+' <button class="secondary small" data-status="found">Ändra anmärkning</button></div>':''}${a.previousStatus?'<details class="previous-status"><summary>Tidigare status före nya plockflödet</summary>'+esc(({missing:'Saknas',found:'Hittad',notfound:'Inte hittad'})[a.previousStatus.status]||a.previousStatus.status)+'</details>':''}</div>`;
}
function renderArticles(){
 let o=current();if(!o)return;let q=norm($('search').value),arr=sectionOrder(o).articles.filter(a=>{let x=data.stock[norm(a.nr)]||{};if(a.isGroup&&(filter!=='all'||sortBy!=='default'))return false;return(filter==='all'||a.isGroup||a.status===filter||(filter==='remaining'&&a.status!=='fetched'))&&norm([a.nr,a.description,x.description,a.location,a.note,a.blockReason,x.location,x.note,(x.previousLocations||[]).join(' ')].join(' ')).includes(q)});
 if(sortBy==='location'||sortBy==='area')arr.sort((a,b)=>{let la=a.location||data.stock[norm(a.nr)]?.location||'',lb=b.location||data.stock[norm(b.nr)]?.location||'';return !la&&!lb?0:!la?1:!lb?-1:la.localeCompare(lb,'sv',{numeric:true})});
 if(sortBy==='known')arr.sort((a,b)=>Number(!!(b.location||data.stock[norm(b.nr)]?.location))-Number(!!(a.location||data.stock[norm(a.nr)]?.location)));
 let content;if(sortBy==='area'&&arr.length){let grouped=new Map();for(const a of arr){let loc=a.location||data.stock[norm(a.nr)]?.location||'',area=loc.match(/^[\p{L}\p{N}]+/u)?.[0]||'Okänd plats';if(!grouped.has(area))grouped.set(area,[]);grouped.get(area).push(a)}content=Array.from(grouped,([area,items])=>`<div class="areahead">${esc(area)} · ${items.length}</div>`+items.map(a=>renderArticle(a,o)).join('')).join('')}else content=arr.map(a=>renderArticle(a,o)).join('');
 $('articles').innerHTML=content||'<div class="empty">Inga artiklar matchar. Prova ett annat sökord eller visa alla.</div>';document.querySelectorAll('.filters button').forEach(b=>{b.classList.toggle('selected',b.dataset.filter===filter);b.setAttribute('aria-pressed',String(b.dataset.filter===filter));});if(typeof renderWorkbench==='function')renderWorkbench(arr.filter(a=>!a.isGroup).length);
}
function renderStock(){let q=norm($('stockSearch').value),list=Object.values(data.stock).filter(x=>norm([x.nr,x.description,x.location,x.note,(x.previousLocations||[]).join(' ')].join(' ')).includes(q)).sort((a,b)=>a.nr.localeCompare(b.nr,'sv',{numeric:true}));$('stock').innerHTML=list.map(x=>{let key=norm(x.nr),previous=(x.previousLocations||[]).length?`Tidigare: ${x.previousLocations.join(', ')}`:'Ingen tidigare plats';return `<div class="stockrow" data-key="${esc(key)}"><div><b>${esc(x.nr)}</b><div class="description">${esc(x.description)}</div><small>${esc(previous)}</small></div><div><label class="sr-only">Lagerplats för ${esc(x.nr)}</label><input data-stock-field="location" value="${esc(x.location)}" placeholder="Lagerplats"></div><div><label class="sr-only">Anteckning för ${esc(x.nr)}</label><input data-stock-field="note" value="${esc(x.note)}" placeholder="Anteckning"></div><div><small>Plats sparad ${date(x.locationUpdated)}</small><small>Hittad ${x.foundCount||0} ${(x.foundCount||0)===1?'gång':'gånger'}</small>${x.lastSeen?`<small>Senast hittad ${date(x.lastSeen)}</small>`:''}<small>${x.locationOrder?'Plats från order '+esc(x.locationOrder):''}</small></div></div>`}).join('')||'<div class="empty">Inga sparade artiklar matchar.</div>';}
function renderCloud(){
 const available=window.Cloud?.available,user=window.Cloud?.user;
 $('passwordLoginForm').classList.toggle('hidden',!available||!!user);
 $('emailLogin').classList.toggle('hidden',!available||!!user);
 $('codeForm').classList.toggle('hidden',!available||!!user||!cloudEmail);
 $('setPasswordForm').classList.toggle('hidden',!user);
 $('signOut').classList.toggle('hidden',!user);
 $('syncConflict').classList.toggle('hidden',!cloudConflict);
 $('cloudStatus').textContent=available?(user?`${cloudMessage} · ${user.email||'Inloggad'}`:cloudMessage):'Molnsynk väntar på ett separat Lagerkollen-konto. Lokal backup fungerar fortfarande.';
}
function checkpoint(){try{return JSON.parse(localStorage.getItem(CHECKPOINT)||'null')}catch(e){return null}}
function markSynced(revision){cloudRevision=revision;try{localStorage.setItem(CHECKPOINT,JSON.stringify({userId:Cloud.user.id,localRevision:data._revision,remoteRevision:revision}))}catch(e){}cloudMessage='Synkad';setSaveState('Synkad');renderCloud()}
function replaceFromCloud(row){data=sanitize(row.payload);cloudRevision=row.revision;cloudConflict=null;let raw=JSON.stringify(data);try{localStorage.setItem(KEY,raw)}catch(e){notice('Kunde inte spara molndata lokalt')}writeMirror(raw).catch(()=>{});markSynced(row.revision);render()}
function hasRecords(value){return value.orders.length>0||Object.keys(value.stock).length>0||Object.keys(value.deletedOrders||{}).length>0||(value.groups||[]).length>0||(value.sections||[]).some(x=>x.updated>0||x.deleted)}
function hasLocalData(){return hasRecords(data)}
function shouldSeedCloud(row,cp,userId){return hasLocalData()&&!hasRecords(row.payload)&&(!cp?.userId||cp.userId===userId)}
function showConflict(row){cloudConflict=row;cloudMessage='Synkkonflikt – välj version i Backup & synk';setSaveState('Synkkonflikt',true);renderCloud();notice('Data finns på båda enheterna. Välj version i Backup & synk.')}
async function initCloud(){if(!window.Cloud?.available){renderCloud();return}try{let user=await Cloud.init((event)=>{if(event==='SIGNED_IN')startCloud().catch(syncError);if(event==='SIGNED_OUT'){cloudRevision=null;cloudConflict=null;cloudMessage='Utloggad – data sparas lokalt';renderCloud()}});if(user)await startCloud()}catch(e){syncError(e)}}
function syncError(e){cloudMessage='Synkfel: '+(e.message||e);setSaveState('Synkfel – lokalt sparad',true);renderCloud()}
async function startCloud(){if(!Cloud.user||cloudBusy)return;cloudBusy=true;cloudMessage='Kontrollerar molndata…';renderCloud();try{let row=await Cloud.read(),cp=checkpoint();if(!row){cloudRevision=null;cloudBusy=false;await pushCloud();return}cloudRevision=row.revision;if(shouldSeedCloud(row,cp,Cloud.user.id)){cloudBusy=false;await pushCloud();return}if(!hasLocalData()||(cp?.userId===Cloud.user.id&&cp.localRevision===data._revision)){replaceFromCloud(row)}else{showConflict(row)}}catch(e){syncError(e)}finally{cloudBusy=false}clearInterval(cloudTimer);cloudTimer=setInterval(()=>pullCloud().catch(syncError),15000)}
function scheduleCloudPush(){if(!Cloud?.user||cloudConflict)return;cloudMessage='Ändringar väntar på synk';renderCloud();clearTimeout(pushTimer);pushTimer=setTimeout(()=>pushCloud().catch(syncError),450)}
let pushTimer;
async function pushCloud(){if(!Cloud.user||cloudBusy||cloudConflict)return;cloudBusy=true;const revisionAtStart=data._revision,copy=JSON.parse(JSON.stringify(data));try{let next=await Cloud.write(copy,cloudRevision);if(next===null){let latest=await Cloud.read();if(latest)showConflict(latest);return}cloudRevision=next;if(data._revision===revisionAtStart)markSynced(next);else{try{localStorage.setItem(CHECKPOINT,JSON.stringify({userId:Cloud.user.id,localRevision:revisionAtStart,remoteRevision:next}))}catch(e){}cloudMessage='Fler ändringar väntar'}}catch(e){syncError(e)}finally{cloudBusy=false}if(data._revision!==revisionAtStart&&!cloudConflict)scheduleCloudPush()}
async function pullCloud(){if(!Cloud.user||cloudBusy||cloudConflict||document.hidden)return;let field=document.activeElement;if(field?.closest('.article,.stockrow'))return;cloudBusy=true;try{let row=await Cloud.read();if(!row){cloudRevision=null;cloudBusy=false;await pushCloud();return}if(row.revision===cloudRevision){let cp=checkpoint();if(cp?.localRevision!==data._revision){cloudBusy=false;await pushCloud()}return}let cp=checkpoint();if(cp?.userId===Cloud.user.id&&cp.localRevision===data._revision)replaceFromCloud(row);else showConflict(row)}catch(e){syncError(e)}finally{cloudBusy=false}}
function mergeData(remote,local){let result=sanitize(remote);local=sanitize(local);result.deletedOrders=Object.fromEntries(Array.from(new Set([...Object.keys(result.deletedOrders),...Object.keys(local.deletedOrders)])).map(id=>[id,Math.max(result.deletedOrders[id]||0,local.deletedOrders[id]||0)]));result.sections=mergeSections(result.sections,local.sections);result.groups=mergeGroups(result.groups,local.groups);let orders=new Map(result.orders.map(o=>[o.id,o]));for(const incoming of local.orders){if(Object.hasOwn(result.deletedOrders,incoming.id))continue;let existing=orders.get(incoming.id);if(!existing){orders.set(incoming.id,incoming);continue}let byId=new Map(existing.articles.map(a=>[a.id,a]));for(const article of incoming.articles){let prior=byId.get(article.id);if(!prior||article.updated>prior.updated)byId.set(article.id,mergeArticle(prior,article))}existing.deletedArticles={...existing.deletedArticles};for(const [id,time] of Object.entries(incoming.deletedArticles||{}))existing.deletedArticles[id]=Math.max(existing.deletedArticles[id]||0,time);existing.articles=Array.from(byId.values()).filter(a=>a.updated>(existing.deletedArticles[a.id]||0));if(incoming.updated>existing.updated){Object.assign(existing,{name:incoming.name,line:incoming.line,subgroup:incoming.subgroup,kind:existing.kind==='picklist'?existing.kind:incoming.kind,productName:incoming.productName||existing.productName,productNr:incoming.productNr||existing.productNr,productionQty:incoming.productionQty??existing.productionQty,printedAt:incoming.printedAt||existing.printedAt,archived:incoming.archived,updated:incoming.updated})}}result.orders=Array.from(orders.values()).filter(o=>!Object.hasOwn(result.deletedOrders,o.id)).map(normalizePicklist).sort((a,b)=>b.created-a.created);for(const [key,x] of Object.entries(local.stock)){let prior=result.stock[key];if(!prior||x.updated>prior.updated){result.stock[key]={...x,previousLocations:Array.from(new Set([...(x.previousLocations||[]),...(prior?.previousLocations||[])]))}}else{prior.previousLocations=Array.from(new Set([...(prior.previousLocations||[]),...(x.previousLocations||[])]))}}result.current=result.orders.some(o=>o.id===local.current)?local.current:(result.orders.some(o=>o.id===result.current)?result.current:(result.orders.find(o=>!o.archived)||result.orders[0]||{}).id||null);return reconcilePlacement(result)}
function render(){refreshLineChoices();renderEditor();renderOrders();renderOrder();renderStock();renderCloud();$('backupMeta').textContent=`${data.orders.length} ordrar · ${Object.keys(data.stock).length} registerartiklar`;}
$('foundForm').onsubmit=e=>{e.preventDefault();if(!pendingFound||current()?.id!==pendingFound.orderId){$('foundDialog').close();return;}if(changeStatus(pendingFound.articleId,'found',$('foundReason').value))$('foundDialog').close();};
$('foundCancel').onclick=()=>$('foundDialog').close();$('foundDialog').addEventListener('close',()=>{pendingFound=null;});
$('newOrderToggle').onclick=()=>{$('newOrderForm').classList.toggle('hidden');if(!$('newOrderForm').classList.contains('hidden')){$('orderName').focus();refreshGroupChoices()}};$('welcomeNew').onclick=startOrder;$('newOrderForm').onsubmit=e=>{e.preventDefault();addOrder($('orderName').value,$('orderLine').value,$('orderGroup').value,$('orderProduct').value)};
$('sectionForm').onsubmit=e=>{e.preventDefault();if(addSection($('sectionName').value))$('sectionName').value='';};
$('headingEditor').addEventListener('submit',e=>{let form=e.target.closest('[data-add-heading]');if(!form)return;e.preventDefault();let name=form.elements.heading.value;if(headingName(name)){ensureGroup(form.dataset.addHeading,name);persist();notice('Underrubrik tillagd');}});
$('headingEditor').onclick=e=>{let rename=e.target.closest('[data-rename-heading]'),remove=e.target.closest('[data-delete-heading]');if(rename){let next=prompt('Nytt namn:',rename.dataset.headingName||rename.dataset.renameHeading);if(next!==null)renameHeading(rename.dataset.renameHeading,rename.dataset.headingName,next);}if(remove)deleteHeading(remove.dataset.deleteHeading,remove.dataset.headingName);};
$('orderLine').onchange=()=>{$('orderGroup').value='';refreshGroupChoices();};
$('placementLine').onchange=()=>fillGroupSelect('placementGroup',$('placementLine').value);
$('placementForm').onsubmit=e=>{e.preventDefault();placeOrder($('placementLine').value,$('placementGroup').value)};
$('deleteOrder').onclick=()=>{if(current())removeOrder(current().id)};
$('orders').onclick=e=>{let b=e.target.closest('[data-order]');if(b){selectOrder(b.dataset.order);return}let group=e.target.closest('[data-add-group]');if(group){let name=prompt('Ny underrubrik i '+group.dataset.addGroup+' (t.ex. Cup, Magma eller Rondo):');if(name?.trim()){ensureGroup(group.dataset.addGroup,name);persist()}return}let create=e.target.closest('[data-new-in-line]');if(create){startOrder();$('orderLine').value=create.dataset.newInLine;refreshGroupChoices();$('orderGroup').value=create.dataset.newInGroup;}};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));$('toggleOrders').onclick=()=>show('orders');$('openBackup').onclick=()=>show('backup');$('stockBack').onclick=$('backupBack').onclick=$('editBack').onclick=()=>show('order');
let pendingRepeat=null;
$('repeatOrder').onclick=()=>{let o=current();if(!o)return;pendingRepeat=o.id;$('repeatName').value=o.name;$('repeatQty').value=o.productionQty??'';$('repeatDialog').showModal();$('repeatName').focus();};
$('repeatForm').onsubmit=e=>{e.preventDefault();if(current()?.id!==pendingRepeat){$('repeatDialog').close();notice('Ordern ändrades. Öppna Kör igen på nytt.');return;}let raw=$('repeatQty').value,qty=optionalNumber(raw);if(raw!==''&&(!(qty>0))){notice('Ange ett antal större än noll.');return;}if(repeatOrder($('repeatName').value,qty))$('repeatDialog').close();};
$('repeatCancel').onclick=()=>$('repeatDialog').close();$('repeatDialog').addEventListener('close',()=>{pendingRepeat=null;});
$('articleSection').onchange=e=>{sectionFilter=e.target.value;renderOrder();};
$('archive').onclick=()=>{let o=current();if(!o)return;o.archived=!o.archived;o.updated=Date.now();persist();notice(o.archived?'Order arkiverad':'Order återöppnad')};
$('copyResults').onclick=async()=>{let order=current();if(!order?.articles.length)return;try{await copyText(formatOrderResults(order));notice(`${order.articles.filter(a=>!a.isGroup).length} ${order.articles.filter(a=>!a.isGroup).length===1?'artikel kopierad':'artiklar kopierade'}. Klistra in i Excel eller ett meddelande.`)}catch(e){notice('Kunde inte kopiera. Prova i Safari eller Chrome.')}};
$('quickAdd').onclick=()=>{if(addArticles($('quickInput').value))$('quickInput').value='';$('quickInput').focus()};$('quickInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();$('quickAdd').click()}};
$('entryToggle').onclick=()=>{let hidden=$('bulkEntry').classList.toggle('hidden');$('entryToggle').setAttribute('aria-expanded',String(!hidden));if(!hidden)$('paste').focus()};$('add').onclick=()=>{if(addArticles($('paste').value))$('paste').value=''};
$('articleFile').onchange=async e=>{let file=e.target.files?.[0];if(!file)return;try{if(file.size>2e6)throw Error('Filen är för stor (max 2 MB)');let raw=await file.text(),parsed=extract(raw);$('paste').value=raw;$('importPreview').textContent=`${parsed.values.length} möjliga nummer. Granska texten och tryck Lägg till nummer.`;$('bulkEntry').classList.remove('hidden');$('entryToggle').setAttribute('aria-expanded','true')}catch(err){notice(err.message)}e.target.value=''};
$('search').oninput=renderArticles;$('stockSearch').oninput=renderStock;$('sort').onchange=e=>{sortBy=e.target.value;renderArticles()};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;renderArticles()});
$('articles').onclick=e=>{let row=e.target.closest('.article');if(!row)return;let s=e.target.closest('[data-status]');if(s)changeStatus(row.dataset.id,s.dataset.status);if(e.target.closest('[data-delete]'))removeArticle(row.dataset.id);if(e.target.closest('[data-use-known]')){let a=current()?.articles.find(a=>a.id===row.dataset.id);if(a)saveField(a.id,'location',data.stock[norm(a.nr)]?.location||'');renderArticles()}};
$('articles').addEventListener('keydown',e=>{if(e.key!=='Enter'||e.target.dataset.field!=='location')return;e.preventDefault();let fields=Array.from(document.querySelectorAll('#articles [data-field=location]')),index=fields.indexOf(e.target),id=e.target.closest('.article').dataset.id;saveField(id,'location',e.target.value);if(fields[index+1])fields[index+1].focus();else e.target.blur()});
$('articles').addEventListener('change',e=>{let row=e.target.closest('.article'),field=e.target.dataset.field;if(row&&['location','note'].includes(field))saveField(row.dataset.id,field,e.target.value)});$('stock').addEventListener('change',e=>{let row=e.target.closest('[data-key]'),field=e.target.dataset.stockField;if(row&&['location','note'].includes(field))updateStock(row.dataset.key,field,e.target.value)});
$('passwordLoginForm').onsubmit=async e=>{e.preventDefault();let email=$('passwordEmail').value.trim(),password=$('passwordLogin').value;$('email').value=email;try{await Cloud.signInWithPassword(email,password);$('passwordLogin').value='';cloudMessage='Loggar in…';renderCloud()}catch(err){$('passwordLogin').value='';syncError(err.message==='Invalid login credentials'?Error('Fel e-post eller lösenord. Använd mejllänk om du behöver skapa ett lösenord.'):err)}};
$('loginForm').onsubmit=async e=>{e.preventDefault();cloudEmail=$('email').value.trim();try{await Cloud.sendLink(cloudEmail);cloudMessage='Kontrollera mejlen och öppna länken på denna enhet. Om mejlet innehåller en kod kan du ange den här.';renderCloud()}catch(err){syncError(err)}};
$('codeForm').onsubmit=async e=>{e.preventDefault();try{await Cloud.verifyCode(cloudEmail||$('email').value.trim(),$('code').value.trim());$('code').value=''}catch(err){syncError(err)}};
$('setPasswordForm').onsubmit=async e=>{e.preventDefault();let password=$('newPassword').value;if(password!==$('confirmPassword').value){notice('Lösenorden matchar inte');return}try{await Cloud.setPassword(password);$('newPassword').value='';$('confirmPassword').value='';notice('Lösenord sparat. Logga in med det på dina andra enheter.')}catch(err){syncError(err)}};
$('signOut').onclick=()=>Cloud.signOut().catch(syncError);
$('useCloud').onclick=()=>{if(!cloudConflict)return;if(!confirm('Ersätta denna enhets data med molnversionen? Exportera en backup först om lokala ändringar ska sparas.'))return;replaceFromCloud(cloudConflict)};
$('mergeCloud').onclick=()=>{if(!cloudConflict)return;let merged=mergeData(cloudConflict.payload,data);cloudRevision=cloudConflict.revision;cloudConflict=null;data=merged;persist();notice('Data sammanslagen och synkas till molnet')};
window.addEventListener('online',()=>pullCloud().catch(syncError));document.addEventListener('visibilitychange',()=>{if(!document.hidden)pullCloud().catch(syncError)});
$('export').onclick=()=>{let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='lagerkollen-backup-'+new Date().toISOString().slice(0,10)+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)};
$('import').onchange=async e=>{let file=e.target.files?.[0];if(!file)return;try{if(file.size>20e6)throw Error('Backupen är för stor');let imported=sanitize(JSON.parse(await file.text()));if(confirm(`Ersätta nuvarande data med ${imported.orders.length} ordrar och ${Object.keys(imported.stock).length} registerartiklar? Exportera gärna nuvarande data först.`)){data=imported;persist();show('order');notice('Backup importerad')}}catch(err){notice('Ogiltig backup: '+err.message)}e.target.value=''};
document.addEventListener('keydown',e=>{let typing=e.target.matches('input,textarea,select,[contenteditable]');if(e.key==='Escape'&&e.target===$('search')){$('search').value='';renderArticles();$('search').blur()}if(typing||e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='/'){e.preventDefault();show('order');$('search').focus()}if(e.key.toLowerCase()==='n'){e.preventDefault();show('order');$('quickInput').focus()}});
window.addEventListener('storage',e=>{if(e.key!==KEY||!e.newValue)return;try{let incoming=sanitize(JSON.parse(e.newValue));if(incoming._revision>data._revision){data=incoming;render();notice('Ändringar från en annan flik laddades')}}catch(err){}});
boot();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
